DROP TABLE __MigrationHistory
DROP TABLE Absences
DROP TABLE BloodSamples
DROP TABLE MaterialWorkOrders
DROP TABLE MedicineWorkOrders
DROP TABLE ActivityInputDatas
DROP TABLE ActivityActivityInputs
DROP TABLE ServiceActivities
DROP TABLE PatientWorkOrders
DROP TABLE Materials
DROP TABLE Medicines
DROP TABLE ActivityInputs
DROP TABLE Activities
DROP TABLE Visits
DROP TABLE WorkOrders
DROP TABLE Employees
DROP TABLE Diseases
DROP TABLE Users
DROP TABLE Patients
DROP TABLE Relationships
DROP TABLE Districts
DROP TABLE Contractors
DROP TABLE Roles
DROP TABLE PostOffices
DROP TABLE IpLogs
DROP TABLE Services