DROP TABLE __MigrationHistory
DROP TABLE dbo.BloodSamples
DROP TABLE MaterialWorkOrders
DROP TABLE MedicineWorkOrders
DROP TABLE PatientWorkOrders
DROP TABLE Materials
DROP TABLE Medicines
DROP TABLE Visits
DROP TABLE WorkOrders
DROP TABLE Employees
DROP TABLE Contractors
DROP TABLE Diseases
DROP TABLE Users
DROP TABLE Patients
DROP TABLE Relationships
DROP TABLE Districts
DROP TABLE Roles
DROP TABLE PostOffices
DROP TABLE Activities
DROP TABLE IpLogs